services:
  namenode:
    image:  bdsa2025/bdsa2025-namenode:3.4.1
    networks:
      - bigdata_net
    volumes:
      - ./volumes/dfs/name:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=BDSA2025
    env_file:
      - hadoop.env
    ports:
      - 9870:9870
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == bde2025_namenode
      labels:
        traefik.docker.network: bigdata_net

  datanode:
    image:  bdsa2025/bdsa2025-datanode:3.4.1
    networks:
      - bigdata_net
    volumes:
      - ./volumes/dfs/data:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata_net

  resourcemanager:
    image:  bdsa2025/bdsa2025-resourcemanager:3.4.1
    networks:
      - bigdata_net
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == bde2025_resourcemanager
      labels:
        traefik.docker.network: bigdata_net
    healthcheck:
      disable: true

  nodemanager:
    image: bdsa2025/bdsa2025-nodemanager:3.4.1
    networks:
      - bigdata_net
    environment:
      SERVICE_PRECONDITION: "resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata_net
  
  historyserver:
    image: bdsa2025/bdsa2025-historyserver:3.4.1
    networks:
      - bigdata_net
    volumes:
      - ./volumes/yarn/timeline:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9870 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188
      - 19888:19888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == bde2025_historyserver
      labels:
        traefik.docker.network: bigdata_net

  edge-spark:
    image:  bdsa2025/bdsa2025-edge-spark:3.4.1
    networks:
      - bigdata_net
    volumes:
      - ./volumes/edge:/mnt
    env_file:
      - ./hadoop.env
    ports:
      - 2222:2222
      - 4040-4140:4040-4140
    privileged: true
    security_opt:
      - seccomp:unconfined
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata_net

#  hiveserver:
#    image: bdsa2025/hive:3.4.1_java-17-hive4.0.1
#    networks:
#      - bigdata_net
#    #volumes:
#    #  - /volumes/metastoredb:/var/lib/mysql
#    #  - /hive-log4j2.properties:/etc/hive/hive-log4j2.properties
#    environment:
#      SERVICE_PRECONDITION: "namenode:9870 resourcemanager:8088"
#    env_file:
#      - hadoop.env
#    ports:
#      - 10000:10000
#      - 10002:10002
#      - 9803:9803
#      - 8080:8080
#      - 3306:3306

    
networks:
  bigdata_net: 
    driver: bridge
